### ISSUE TITLE
検索結果からプロフィールの詳細に飛ばす処理

### ISSUE THREAD

**Issue by Yuta20132** [Yuta20132/musube-react#16]
モーダル化？

**Comment by Yuta20132** [comment]
テスト

**Comment by himegitaichi** [comment]
・モックデータの変更・追加と名前検索機能の向上は完了
・モーダルウィンドウ用にSearchDetailModal.tsxとSearchResultをexportするためSearch.tsを作成し，Search.tsxからSearchResultを移行←イマココ

**Comment by himegitaichi** [comment]
Search.tsxにモーダルウィンドウを表示するコードを追加したのですが，なぜか点滅します．

https://github.com/user-attachments/assets/e29e43d3-5170-4840-b6f4-82fb47b24e24

**Comment by himegitaichi** [comment]
一応pushしてます

**Comment by Yuta20132** [comment]
点滅についてだけどuseEffectではなくてuseStateを使えば解消されると思うよ
GPTを使うの大事だけど，公式ドキュメントも見てね

https://mui.com/material-ui/react-modal/

**Comment by himegitaichi** [comment]
なるへそ，勉強になりやす！
