### ISSUE TITLE
登録ページの処理

### ISSUE THREAD

**Issue by Yuta20132** [Yuta20132/musube-react#8]
パスワードと確認パスワードが同じときしかPUTできない。
研究者か大学を選んだときは，メールアドレスはac.jpに限定する。

今後増やしていく。

**Comment by himegitaichi** [comment]
姫城やります

**Comment by Yuta20132** [comment]
パスワードと確認パスワードが同じときしかPUTできない。

別isuuesで対応済み

**Comment by Yuta20132** [comment]
https://github.com/Yuta20132/musube-react/pull/17

上記プルリクエストで対応済み
